# Generated by Django 3.1.3 on 2020-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='images',
            field=models.ImageField(height_field='10', upload_to='home_slider', width_field='10'),
        ),
    ]
