# Generated by Django 3.1.3 on 2020-12-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201209_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
